#!/usr/bin/python3.7

####################################################
ERROR_LORA_BASE_STATION = "ERROR_LORA_BASE_STATION"
ERROR_BUFFER_TX_OVERFLOW = "ERROR_BUFFER_TX_OVERFLOW"
ERROR_INVALID_HW_ID = "ERROR_INVALID_HW_ID"
ERROR_INVALID_LORA_ADDRESS = "ERROR_INVALID_LORA_ADDRESS"
ERROR_INVALID_VERSION = "ERROR_INVALID_VERSION"
ERROR_LORA_NETWORK = "ERROR_LORA_NETWORK"
ERROR_DATA_LENGTH_RECEIVED = "ERROR_DATA_LENGTH_RECEIVED"
ERROR_UNKNOWN_RECEIVED_COMMAND = "ERROR_UNKNOWN_RECEIVED_COMMAND"
ERROR_METADATA_RECEIVED_EMPTY = "ERROR_METADATA_RECEIVED_EMPTY"
ERROR_WRONG_PARAMETERS = "ERROR_WRONG_PARAMETERS"
ERROR_CRC_RECEIVED = "ERROR_CRC_RECEIVED"
ERROR_DATA_COMMING_FROM_OTHER_DEVICE = "ERROR_DATA_COMMING_FROM_OTHER_DEVICE"
OK = "OK"
####################################################

